import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LogInProvider } from "./_context/UserLogIn";
import { NameProvider } from "./_context/UserName";
import { EmailProvider } from "./_context/UserEmail";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex `}
      >
        <NameProvider>
          <EmailProvider>
            <LogInProvider>{children}</LogInProvider>
          </EmailProvider>
        </NameProvider>
      </body>
    </html>
  );
}
